### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by yochimonji** [plant-management/hachiue-backend#2]
## ✨ Summary

FastAPIの環境を構築する。

## 🔥 Requirements

- Remote Container上で編集できる
- Linter, Formatter使える

## 📄 References

- [FastAPI入門](https://zenn.dev/sh0nk/books/537bb028709ab9)
- [Poetryをサクッと使い始めてみる](https://qiita.com/ksato9700/items/b893cf1db83605898d8a)

## ✅ Tasks

- [x] Dockerを設定
- [x] Remote Container上で動かす
- [x] flake8, black, isort, mypy
- [x] VSCodeの設定

**Comment by hoimas** [comment]
良いと思います
